# -*- coding: utf-8 -*-
{
    'name': "Electronic Document Tracking System",
    'summary': """Electronic Document Tracking System""",
    'description': """Electronic Document Tracking System""",
    'author': "Philip Lloyd Feliprada",
    'version': '13.0.1',
    'depends': [
        'base',
        'mail',
        'account',
        'account_accountant',
        'purchase',
        'admin_vendor',
        'admin_api_connector',
        'company_and_branch_code',
        'contact_unique_id_number',
        'edts_reason',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/email_templates.xml',
        'data/cron.xml',

        'views/settings.xml',
        'views/ir_sequence.xml',
        'views/account_account.xml',
        'views/account_journal.xml',
        'views/account_move.xml',

        'views/edts_search_views.xml',
        'wizard/transfer_wizard.xml',
        'wizard/submit_wizard.xml',
        'wizard/signature_wizard.xml',
        'wizard/reason_wizard.xml',
        'wizard/countered_wizard.xml',
        'wizard/payment_reference_line_wizard.xml',
        'wizard/liquidation_reference_wizard.xml',
        'views/edts_cmc_type.xml',
        'views/payment_reference_line.xml',
        'views/liquidation_reference_line_type.xml',
        'views/liquidation_reference.xml',
        'views/liquidation_reference_line.xml',
        'views/edts_tree_views.xml',
        'views/edts_action_windows.xml',
        'views/edts_menus.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False
}
